# Header
menu:
  - title: '首页'
    url: ''
  - title: '归档'
    url: 'archives'
rss: /blog/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
